FROM mcr.microsoft.com/vscode/devcontainers/base:0-buster

# RUN apt-get update && apt-get install --no-install-recommends -y \
#     vim

# python
RUN curl https://pyenv.run | bash

# shell
RUN echo "bindkey -v" >> /home/node/.zshrc
